package model;

// This class represents a single payslip record as generated by the payslip_generation view.
// Its fields directly map to the columns of your SQL view.
public class Payslip {

    private String payslipNo;
    private String employeeId;
    private String employeeName;
    private String periodStartDate;
    private String periodEndDate;
    private String employeePosition;
    private double monthlyRate;
    private double dailyRate;
    private int daysWorked;
    private double overtime;
    private double grossIncome;
    private double riceSubsidy;
    private double phoneAllowance;
    private double clothingAllowance;
    private double totalBenefits;
    private double socialSecuritySystem;
    private double philhealth;
    private double pagIbig;
    private double withholdingTax;
    private double totalDeductions;
    private double takeHomePay;

    // Constructor to populate all fields from the database view
    public Payslip(String payslipNo, String employeeId, String employeeName, String periodStartDate,
            String periodEndDate, String employeePosition, double monthlyRate,
            double dailyRate, int daysWorked, double overtime, double grossIncome,
            double riceSubsidy, double phoneAllowance, double clothingAllowance,
            double totalBenefits, double socialSecuritySystem, double philhealth,
            double pagIbig, double withholdingTax, double totalDeductions,
            double takeHomePay) {
        this.payslipNo = payslipNo;
        this.employeeId = employeeId;
        this.employeeName = employeeName;
        this.periodStartDate = periodStartDate;
        this.periodEndDate = periodEndDate;
        this.employeePosition = employeePosition;
        this.monthlyRate = monthlyRate;
        this.dailyRate = dailyRate;
        this.daysWorked = daysWorked;
        this.overtime = overtime;
        this.grossIncome = grossIncome;
        this.riceSubsidy = riceSubsidy;
        this.phoneAllowance = phoneAllowance;
        this.clothingAllowance = clothingAllowance;
        this.totalBenefits = totalBenefits;
        this.socialSecuritySystem = socialSecuritySystem;
        this.philhealth = philhealth;
        this.pagIbig = pagIbig;
        this.withholdingTax = withholdingTax;
        this.totalDeductions = totalDeductions;
        this.takeHomePay = takeHomePay;
    }


    public String getPayslipNo() {
        return payslipNo;
    }

    public String getEmployeeId() {
        return employeeId;
    }

    public String getEmployeeName() {
        return employeeName;
    }

    public String getPeriodStartDate() {
        return periodStartDate;
    }

    public String getPeriodEndDate() {
        return periodEndDate;
    }

    public String getEmployeePosition() {
        return employeePosition;
    }

    public double getMonthlyRate() {
        return monthlyRate;
    }

    public double getDailyRate() {
        return dailyRate;
    }

    public int getDaysWorked() {
        return daysWorked;
    }

    public double getOvertime() {
        return overtime;
    }

    public double getGrossIncome() {
        return grossIncome;
    }

    public double getRiceSubsidy() {
        return riceSubsidy;
    }

    public double getPhoneAllowance() {
        return phoneAllowance;
    }

    public double getClothingAllowance() {
        return clothingAllowance;
    }

    public double getTotalBenefits() {
        return totalBenefits;
    }

    public double getSocialSecuritySystem() {
        return socialSecuritySystem;
    }

    public double getPhilhealth() {
        return philhealth;
    }

    public double getPagIbig() {
        return pagIbig;
    }

    public double getWithholdingTax() {
        return withholdingTax;
    }

    public double getTotalDeductions() {
        return totalDeductions;
    }

    public double getTakeHomePay() {
        return takeHomePay;
    }

}
